### ISSUE TITLE
[BUG] "Failed to query available provider packages" despite terraform packages being available

### ISSUE THREAD

**Issue by mogul** [pivotal/cloud-service-broker#99]
My brokerpak attempts to use the Terraform registry despite provider packages being available locally.

## Description
GIVEN the file `manifest.yml` contains (note the version of Terraform):
```
packversion: 1
name: solr-services-pak
version: 1.0.0
metadata:
  author: [redacted]
platforms:
- os: linux
  arch: "386"
- os: linux
  arch: amd64
terraform_binaries:
- name: terraform
  version: 0.13.3
  source: https://github.com/hashicorp/terraform/archive/v0.13.3.zip  
- name: terraform-provider-random
  version: 2.3.0
  source: https://releases.hashicorp.com/terraform-provider-random/2.3.0/terraform-provider-random_2.3.0_linux_amd64.zip
- name: terraform-provider-kubernetes
  version: 1.13.2
  source: https://releases.hashicorp.com/terraform-provider-kubernetes/1.13.2/terraform-provider-kubernetes_1.13.2_linux_amd64.zip
- name: terraform-provider-helm
  version: 1.3.0
  source: https://releases.hashicorp.com/terraform-provider-helm/1.3.0/terraform-provider-helm_1.3.0_linux_amd64.zip
service_definitions:
- services/solr-operator.yml
parameters: []
required_env_variables: []
env_config_mapping: {}
```
...AND the file `services/solr-operator.yml` contains:
```
version: 1
name: solr-operator
id: f145c5aa-4cee-4570-8a95-9a65f0d8d9da
description: Fault-tolerant and highly-available distributed indexing and searching using Apache Solr, in the Kubernetes cluster of your choice
display_name: Apache SolrCloud
image_url: https://lucene.apache.org/theme/images/solr/identity/Solr_Logo_on_white.png
documentation_url: https://lucene.apache.org/solr/resources.html
support_url: https://github.com/GSA/solr-brokerpak
tags: [apache, search, index, k8s]
plans:
- name: base
  id: 1779d7d5-874a-4352-b9c4-877be1f0745b
  description: Establish a beachhead in the provided k8s where you want SolrCloud services available
  display_name: SolrCloud beachhead in k8s
  bullets:
  - "REQUIRED prerequisite: Create an operator before creating instances of the SolrCloud service"
  properties: {}
provision:
  plan_inputs: []
  user_inputs:
  - required: true
    field_name: cluster_id
    type: string
    details: The cluster ID to target from the passed kubeconfig
  - required: true
    field_name: ingress_base_domain
    # Does the customer have to know? Can we derive this from an existing ingress
    # controller in the provided k8s?
    type: string
    details: "The base domain to expose Solr on, eg *.(ingress-base-domain)"
  - required: false
    field_name: operator_name
    type: string
    details: The namespace to use (only specify for demo purposes)"
  computed_inputs: 
  - name: operator_name
    default: ""
    overwrite: false
    type: string
  outputs:
  - required: true
    field_name: operator
    type: string
    details: The name of the operator, to be used when creating SolrCloud instances
  template_ref: "services/solr-operator/operator-provision.tf"
bind:
  plan_inputs: []
  user_inputs: []
  computed_inputs:
  - name: operator
    default: ${instance.details["operator"]}
    overwrite: true
    type: string
  outputs:
  - required: true
    field_name: operator
    type: string
    details: The name of the operator, to be used when creating SolrCloud instances
  template_ref: "services/solr-operator/operator-bind.tf"
examples:
- name: Create an operator in Docker Desktop
  description: "This example creates an operator in a local k8s provided by
  Docker Desktop. It's presumes the k8s already has an ingress controller
  available that will handle ing.local.domain."
  plan_id: 1779d7d5-874a-4352-b9c4-877be1f0745b
  provision_params:
    cluster_id: docker-desktop
    ingress_base_domain: ing.local.domain
  bind_params: {}
- name: Create an operator in Docker Desktop in the default namespace
  description: "This example creates an operator in a local k8s provided by
  Docker Desktop. It's presumes the k8s already has an ingress controller
  available that will handle ing.local.domain. The `default` namespace will be
  used in order to make it easy to demonstrate a provisioned SolrCloud in the
  ing.local.domain later."
  plan_id: 1779d7d5-874a-4352-b9c4-877be1f0745b
  provision_params:
    cluster_id: docker-desktop
    ingress_base_domain: ing.local.domain
  bind_params: {}
plan_updateable: false
requiredenvvars: []
```
AND I have run the CSB to create the brokerpak
AND I have run the CSB with the brokerpak with the `serve` parameter
WHEN I run `cloud-service-broker client provision --instanceid myoperator --serviceid f145c5aa-4cee-4570-8a95-9a65f0d8d9da  --planid 1779d7d5-874a-4352-b9c4-877be1f0745b --params '{"cluster_id":"docker-desktop", "ingress_base_domain":"ing.local.domain"}'`

## Expected Behavior
...THEN I should see a 2xx response indicating that the service instance was created

## Actual Behavior
...BUT I see:
```
{
    "url": "http://user:pass@broker:80/v2/service_instances/myoperator?accepts_incomplete=true",
    "http_method": "PUT",
    "status_code": 500,
    "response": {
        "description": "Error: Failed to query available provider packagesCould not retrieve the list of available versions for providerhashicorp/random: provider registry.terraform.io/hashicorp/random was notfound in any of the search locations- /tmp/brokerpak000473515Error: Failed to query available provider packagesCould not retrieve the list of available versions for providerhashicorp/kubernetes: provider registry.terraform.io/hashicorp/kubernetes wasnot found in any of the search locations- /tmp/brokerpak000473515Error: Failed to query available provider packagesCould not retrieve the list of available versions for provider hashicorp/helm:provider registry.terraform.io/hashicorp/helm was not found in any of thesearch locations- /tmp/brokerpak000473515 exit status 1"
    }
}
```

## Possible Fix
 I suspect this may be due to [changes in how Terraform works with the registry as of `0.13.x`](https://www.hashicorp.com/blog/announcing-hashicorp-terraform-0-13).

## Steps to Reproduce
Check out [this particular branch](https://github.com/GSA/template-brokerpak/tree/helm-prototype). Run:
```
cp .env.secrets-template .env.secrets
make build
make up
make test
```

## Context
I'm trying to create my own brokerpak, but I can't get the brokerpak to work despite including provider packages matching my local Terraform config:
```
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/helm v1.3.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.2
+ provider registry.terraform.io/hashicorp/random v2.3.0
```

## Your Environment

* Version used: v0.7.1-beta
* Operating System and version (desktop): Mac OS X 10.14.6
* Link to your project (if public): https://github.com/GSA/template-brokerpak/tree/helm-prototype
* Platform (Azure/AWS/GCP): N/A, my service currently runs only in a locally available k8s
* Applicable Services: N/A
